language: php
sudo: false

matrix:
    include:
      - php: 7.0

services:
    - redis

cache:
    directories:
      - "$HOME/.composer/cache"

before_install:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - ./build/php/7.0/Apcu.sh

install:
    - composer update

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - pip install --user codecov && codecov

notifications:
    email: false
